language: go

go:
  - "1.12beta1"

env:  
  - GO111MODULE=on

install:
  - GO111MODULE=off go get github.com/codeclimate/test-reporter

before_script:
  - test-reporter before-build

script:
  - go test -coverprofile c.out ./...

after_script:
  - test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
