language: go

go:
  - "1.12beta1"

env:  
  - GO111MODULE=on

install:
  - mkdir -p $GOPATH/src/github.com/codeclimate && cd $GOPATH/src/github.com/codeclimate && git clone https://github.com/codeclimate/test-reporter.git && cd $GOPATH/src/github.com/codeclimate/test-reporter && go install

before_script:
  - test-reporter before-build

script:
  - go test -coverprofile c.out ./...

after_script:
  - test-reporter after-build --exit-code $TRAVIS_TEST_RESULT